version = "1.0.0"

[[files]]
file = "license/Cargo.toml"
expr = 'version = "(.*)"'

[[files]]
file = "xtask/Cargo.toml"
expr = 'version = "(.*)"'

[[files]]
file = "sonar-project.properties"
expr = "sonar.projectVersion=(.*)"

[package]
