[package]
name = "xtask"
version = "1.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
publish = false

[dependencies]
current_platform = "0.2"
license-gen-bin = { path = "../license" }
clap.workspace = true
clap-verbosity-flag.workspace = true
color-print.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
clap_complete = "4.6"
clap_mangen = "0.3"
devx-cmd = "0.5"
devx-pre-commit = "0.5"
zstd = { version = "0.13", features = ["zstdmt"] }
tar = "0.4"
num_cpus = "1.17"
sha2 = "0.11"
ctrlc = "3.5"
hex = "0.4"
